#ifndef SVC_HANDLER_H
#define SVC_HANDLER_H

#define SVC_YIELD_SWITCH 0U
#define SVC_YIELD_SWITCH_CMD "SVC #0"

#define SVC_YIELD_SWITCH_PREEMPTIVE 1U
#define SVC_YIELD_SWITCH_PREEMPTIVE_CMD "SVC #1"

#endif // SVC_HANDLER_H
