#ifndef SVC_HANDLER_H
#define SVC_HANDLER_H

#define SVC_YIELD_SWITCH 0U
#define SVC_YIELD_SWITCH_CMD "SVC #0"

#define SVC_YIELD_SWITCH_NO_RESET 1U
#define SVC_YIELD_SWITCH_NO_RESET_CMD "SVC #1"

#endif // SVC_HANDLER_H
